# Generated by Django 5.2.11 on 2026-02-24 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airesume_app', '0002_exam_questionscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airesume_app.user'),
        ),
    ]
